import type { NextApiRequest, NextApiResponse } from 'next'
import nodemailer from 'nodemailer'

// Cache across requests in dev
let cachedTestAccount: nodemailer.TestAccount | null = null
let cachedTransporter: nodemailer.Transporter | null = null

async function getTestTransporter() {
  if (cachedTransporter && cachedTestAccount) return { testAccount: cachedTestAccount, transporter: cachedTransporter }
  const testAccount = await nodemailer.createTestAccount()
  const transporter = nodemailer.createTransport({
    host: testAccount.smtp.host,
    port: testAccount.smtp.port,
    secure: testAccount.smtp.secure,
    auth: {
      user: testAccount.user,
      pass: testAccount.pass,
    },
  })
  cachedTestAccount = testAccount
  cachedTransporter = transporter
  return { testAccount, transporter }
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  if (process.env.NODE_ENV === 'production') return res.status(403).json({ error: 'Not allowed in production' })

  try {
    const body = req.body || {}
    const to = (body?.to as string) || process.env.SMTP_FROM || 'recipient@example.com'
    const { testAccount, transporter } = await getTestTransporter()

    const info = await transporter.sendMail({
      from: `Portfolio Test <${testAccount.user}>`,
      to,
      subject: 'Portfolio dev test email (Ethereal)',
      text: 'This is a test email generated by Ethereal via nodemailer.',
    })

    const previewUrl = nodemailer.getTestMessageUrl(info)
    const payload = {
      accepted: (info as any).accepted,
      rejected: (info as any).rejected,
      envelope: (info as any).envelope,
      messageId: (info as any).messageId,
      response: (info as any).response,
    }

    return res.status(200).json({ ok: true, previewUrl, info: payload })
  } catch (err) {
    console.error('pages test email error', err)
    return res.status(500).json({ error: 'Failed to send test email' })
  }
}
